// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgenpg

import (
	"database/sql"
)

type ProcessChannel struct {
	Name      string
	Channel   string
	Version   int32
	UpdatedAt int64
}

type ProcessDefinition struct {
	Name        string
	Version     int32
	Definition  string
	ContentHash string
	CreatedAt   int64
}

type ProcessDependency struct {
	ParentName    string
	ParentVersion int32
	StepID        string
	ChildIdx      int32
	ChildName     string
	ChildVersion  int32
}

type ProcessInstance struct {
	ID             string
	ProcessName    string
	ProcessVersion int32
	StepQueue      string
	ContextData    string
	ParentID       string
	CallStack      string
	RetryCount     int32
	NextRetryAt    sql.NullInt64
	Status         string
	Error          string
	CreatedAt      int64
	UpdatedAt      int64
	WorkerID       sql.NullString
	LeaseExpiresAt sql.NullInt64
}
